{{- if .Values.ldapSecret.create -}}
apiVersion: v1
metadata:
  name: {{ .Values.ldapSecret.name | default (printf "%s-ldap-config" .Release.Name) }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
kind: Secret
type: Opaque
stringData:
  {{- toYaml .Values.ldapSecret.stringData | nindent 2 }}
{{- end }}
